---
author: "Ben Chu"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)

library(RWordPress)
library(knitr)

options(WordpressLogin = c('chubenn' = 'FarsightedFlamingo1'),
        WordpressURL = 'https://chubenn.blog/xmlrpc.php')

knit2wp("Self Help or how to extend your stay in limbo and other vaguely hellish places..Rmd", 
        title = "Self Help or how to extend your stay in limbo and other vaguely hellish places.", 
        action = c("newPost"), 
        publish = FALSE)
```
[This is the extended format for an article found in *Poverty Scam - December 2018 - "Self Help."*]

New Year's Resolutions[^1] will always be popular, no matter what the year; especially as our physical literal lives get shorter[^2]. There is increasing demand for self-help[^3], which has arisen from men and women standing in front of a mirror and realizing that their own achievements have made them happy, and maybe they can help other people[^4]. I was browsing through the particular section of a used book store when I found an biography of William S. Burroughs that was incorrectly shelved, but this error has a particular humourous charm[^5].

Today marks month 5 in this journey that other people call sobriety, tempererence, or on(or off) the wagon. I guess I should mention something more about it to clarify any questions. I started it at my parents home, broke, broken, and after the break up. People are supposed to use parisologic language to obfuscate what actually happened while presenting afectatiously: "It was a dark time" - "I didn't want to do anything I would regret." It's obvious to everyone though nobody wants to say it: you just wanted to end it all - cash out your 401k, barter with Charon, meet the ropemaker - suicide[^6]. Which through latent variables, partially explains why I quit drinking (after a particularly long rolling brownout/blackout, I woke up on the floor of my room with a half written, boring suicide note)[^7],[^8].

Though, with this stoic phase called sobriety, there is a short list of pros. I don't have the "I just woke up with a hangover - kill me[^9]." Which leads to a whole host of options: having money, being able to exercise everyday[^10] instead of spending an entire day recouping. One concern: where I am in the process - physically, do I have the same bright red face all the time? What about the jaundiced eyes? The jeroboatic belly - is it getting smaller or am I just becoming more narcissistic? There are loads of before/after pictures on the internet in which people post their progression with follow up comments "Great Job!" or "Keep going." It's hard not to share in that glory when you imagine posting your own series of pictures. It's a bartering process, one picture for one praise. 

Another process that is up for scrutiny is the cognitive process, the mental one, what's inside the black box hidden in the back of our brains incase of a total accident. I notice an increase in my cognitive load and a decrease to my limits to being burned out[^11]. I can remember mental objects more often, names or events that I want to look up, promises and obligations I made to friends, even the peripheral phenomenons like - what are my overall goals for the day/week/month. This process holds more than just memory - processing. I can walk myself through a proverbial color-by-numbers if they were everyday events; this-that-this-that then my day is done. 

However, there's an one aspect of unequivocal importance that I've never really appreciated[^12] until now, which is the emotional dulling that is brought through alcohol. The certain approach to desiring numbness after a series of traumatic events. Alcohol serves as the disconnects between reality and emotions. Often times, I used it to inveigle the truth, to suppress that fact that deep down inside, I'm not a real human. Now that this suppression effect is gone, I have to firstly grieve for the loss of the temporary alleviating of my trauma, then the trauma itself. 

One of our greatest misconceptions is our understanding of the withdrawal stage, especially from the perspective of casual readers, families, friends, and of course, addicts. Specifically that once the offending substance has been dispelled from the body byway of detoxification, life immediately becomes normal and perfect and happy and unshakeable. This great deception, is the sole reason why Americans are unable to see anything farther than ten feet away. We only see the success stories, the progression pictures, the before-and-afters', the what happens after I quit this after twenty days. 

Detoxification is the first stage of a dual-stage process. With alcohol, it has a massive range of ill-effects: headache, insomnia, vomiting, depression, coma, and even death. The more physical effects: sweating, fatigue, nausea, etc tend to happen immediately/few hours, which taper off from a highest point. Those emotional/mental effects usually come on in few days, delirium tremens[^13] which serve in the form of confusion, hallucinations, and dissociation. The second stage is called post-acute withdrawal, which is more than just than just cravings or irritability. This stage IS that whole, "becoming normal and perfect and happy and unshakeable." 

PAWs can last anywhere from 2 weeks to 7 years[^14] and can be thought of the shift from physical symptoms to those more internal symptoms that test your emotional coping skills and your normalization back into an equally unhealthy society. The brain's neurochemistry begins to regulate itself which brings a variety of tests to find limits and possibilities, which may have never been explored previously. This is a massive  hill-focused motorcycle-ride[^15] of unexplorable emotions filled with anger and a loss of control with every action feeling undermining and overbearing to your lower-than-statistically-reasonable success with a cherry-on-top social isolation. Fantastic, "For I am embarking on the holy quest." Every single article/essay/post you can find on withdrawal has a bolded, heading size large, paragraph spaced section title "practice self care" which highlights the importance, relaxation, and engaging in self-care. However, those articles never seem to tell any sort of *truth*, which I will underline, <u>You may not relapse, but you will fail in each and every endeavour</u>. Next time you browse around and stumble upon a collection of pithy platitudes remarking the importances of failure with quotes from Bruce Lee or Hunter. S Thompson or any semi-successful old man looking into the skyline - disregard it because, <u>repeated failure will not drive you to do better, It simply disintegrates the success/failure continuum</u>. Post Acute Withdrawal Syndrome is more than the mental or emotional or social changes, it is understanding that every aspect of your life that originally provided you with a reward or a sense of control, inevitably erupts in a final flame, leaving only toxic ash. Libations with friends at the bars during the holidays will never be exciting again, racing to happy hour will never provide solace from the anguish of working a long day, holding long enthusiastic conversations with family morphs into dreary heart-breaking engagements, and that tiny globule filled with alcoholic tincture will not spur the creative ideas during a germinal writing phase. The count-down elimination clock begins; one-by-one mawkish beliefs are forfeited until one remains - <u>success/failures are not juxtapositions, rather they do not exist at all</u>.

My initial belief lied in the fact that "alcohol makes life better" but the inverse has served to become more true. "Alcohol makes life less shitty." Addicts generally follow this trend: as stressors increase, consumption of substances increase, acting as a buffer to those life stressors, leading to a tapered version of life[^16]. Those in recovery follow a much more violent trend: as stressors increase, consumption of substances are null, and stressors are experiences in full, leader to a existence full of perceived negative outcomes. Early recovery tends to be incredibly frustrating and bloated with situations which produce blistering distress and pain, which form a feedback loop with no drain off. For me, the lack of emotional dulling amplifies the effects of anger while producing a sense of self-awareness mixed with some feeling of superiority because "I am doing something sacrificially hard that is only found through suffering." As if I acted like an Ultron-type character "no strings on me", but instead of orotund Ultron [^17], I am baby Groot, angst ridden and weaker than I was before. 

I miss drinking alcohol or liquor or beer or wine or cider or cocktails or any invariably disgusting-but-it-gets-the-job-done. It made me believe that I was the best version of who I could be, because I am not much - average physical strength, average cognitive abilities, average looks, average education, average income. That builds an even greater case, to start again[^18]. So with that being said, yea, new beginnings, new year, but if it's anything like the previous 28 years, then it's nothing special at all. It's been 5 months now, but I've been trudging along already dead. I am just waiting for my body to catch up. 

This particular brand of self  help has made me realize that being dependent on alcohol can get you through life because it's so consistent and stable. People understand the effects of alcohol. It's defining. It's forgiving. Most importantly, it confirms what you already know while allowing you to suppress your emotions; ideally until the end of all of our despair-diseased lifes. 

When Burroughs, Ginsberg, Ginsberg's lover, and Kerouac were editing Naked Lunch, they asked Burroughs what he would do if he went back in time "Would you stop yourself from being a junkie?" Burroughs puts down his paper, looks at three and says "I never had a choice anyways." His one and a half decade relationship with heroin ended with him in a claustrophobic room in Morocco, in a permanent state of felonious hiding and running after shooting his then-wife in the head while drunkenly playing "*Our William Tell Act*"[^19] - a game they had never played before. 

The self-help section of my local Goodwill is the largest of all the books, which might suggest that it's the most disposably donated, possibly from strangers who understand that they need change, but did not have a "let's-play-William-Tell" moment to act as a catalyst for real change. Which is to say, buying a self-help book is simply not enough, reading that book will not present change itself, engaging in self-help for 5 months cannot revolutionize your life - the positive change you want to see in your life only comes from sitting down and repeating "I am helpless" until Semantic Satiation[^20] occurs permanently and those words lose all meaning.

*At time of publication: Author has not yet drunkenly relapsed and is on the 6th month.*

***

[^1]: Statistica and Marist Institute for Public Opinion, survey aggregators, suggests that around forty-percent of Americans make some sort of resolution. Saving money at fifty-three percent, losing weight at forty-five percent, the list continues down in that fashion concerning private improvement of some sort. Dauntlessly promiscuously however, 25 percent wish to have more sex while only 15 percent wish to find love. Overall, resolutions themselves are quite frangible, eighty percent give up by the time the end of february, at the end of the year, only 8 percent still accomplishing their goals. This might suggest that goals when established simply to set goals, may not be direction for self improvement, maybe the development we are looking for has to begin at the bottom of the pit. Like *Batman*.
[^2]:  CDC and NCHS, December 2018 reported that life expectancy has dropped for the third year driven largely by deaths from drug overdose, health problems, and suicide. The statistics provided suggested that the fall out from Nobel Prizewinners Case and Deaton's *Mortality and Morbidity in the 21st Century* which discusses the "Diseases of Despair - Drug Abuse, Alcoholism, Diabetes/Heart, and Suicide" are finally become painfully obvious in waking life. These afflictions have taken center stage in social media awareness and federal bills - 3 billion dollars allocated for research, which still only shadows HIV/AIDS at 32 billion and the greater problem, which is the federal shrinking of budget for a problem that costs the U.S. potentially more than 50 billion dollars a year.
[^3]: The self-help industry was valued at eleven billion dollars in 2008. Which suggests that Americans partially believe that the combination of consumerism and self-medicating through books can cure those Diseases of Despair. My liberal arts education suggested that the illusion was "The claim that people needed to work harder, to bootstrap tighter was a lie, that too many other uncontrollable predictors worked against you", when I personally believe that there was never an illusion or bootstrapping or effort or social-economic status, rather the human spirit is so creative that we conjured up purpose and belief and spirit in a world that simply has nothing to offer. 
[^4]: For money or sex - preferably both. 
[^5]: Born into wealth, Burroughs is widely credited with influencing/founding the beat generation - exploring the depths of the human experience through omni-substance fueled mysticism. *Junkie* and *Naked Lunch* non-traditionally explore drug culture and its' effects on the psyche. His personal notes list dozens of opioid treatments but only credits one method to succeed in break his addiction - Apomorphine.
[^6]: When you think about it, it's assuagely pathological - to utilize euphimisms because it perfectly fits how we view (as a society) approach that one topic of suicide. However, I'm going to approach these footnotes from my perspective as an Asian-American. Mental illness holds a stigma in all cultures/people/eras, especially within populations of color (migrants), however when you look at the Chinese-American culture it's somehow encapsulates the entirety of the negative emotion spectrum. Koko Nishi of George Washington University found evidence that Asian-Americans are less likely to seek psychiatric services compared to a nationwide general population. That is, 8.6% percent of Asian-Americans compared to 18%. The why is pretty straightforward - shame/humiliation/fear that's structural to the perspective of the minority. It's hard being "smart" or "nice" or "functional", it's even harder to hide the lie that one might not be. Imagine that shame being brought out to the public (like it is now) and ruminating on those changes to how people view you/your family/your lineage or more specifically, how those own people would view you. Which heaven forbid, if my parents saw this they would say something like "I'm sorry, we didn't know, if we knew we would have gotten you help!" Which is valid, but you didn't know. On top of that, the guilt is almost additive, guilt for having guilt, which then proceeds to - more guilt. You take all that guilt and cover it with a nice plop of stoicism and it festers into a nice mental illness - completely nullifying all that hard work and effort and repression of feelings and "can do it"-bootstrapping-ends-justify-the-means-sacrificial beliefs you thought were going to fix the problem.
[^7]: "I'm sorry mom and dad - I hope my body doesn't leave a mess."
[^8]: This is another misconception brought on by media, a small percentage of people who commit suicide leave notes - a range from 15-20%. Often times, they don't name names, discuss emotional plights, or provide a last relief. The most common theme is often trivial instructions that might be out of sync after death. "Feed the plants." "Cancel the paper." 
[^9]: Another brilliant euphemism, which suggests that this event in particular is worse than death, or maybe, death is the ultimate cure all for particularly bad hangovers? 
[^10]: This is from sheer boredom. However, one of my unintended goals is to be able to do a no-legs hands-only rope pull up. In the event of a hanging gone wrong due to miscalculation of rope length. If the rope is too long, decapitation occurs, that is the severing of the head from the body. Snapping the neck requires 1,260 pounds of force  which severs the spiral cord and brain death commences immediately. The length required is usually around 7 to 9 feet, however the exact calculation is 1,260 divided by the weight of the victim. If the rope is too short, then strangling occurs which often lasts 15 minutes and can be quite painful. Short-Rope-hanging crushes the anatomical neck structures leading to asphyxiation and rupturing of the muscles. Torn muscles and and blood-based trauma can be found throughout the body, hemorrhaging in the sternocleidomastoid muscles are the most common but in some cases, the Teres Major, Pectoralis Major, etc are found to be torn due to people trying to pull up the rope. [INTERPOLATION] The slang phrase "well-hung" references erect penises resulting from the physiological response of a snapped spinal column which leads to the medical condition of priapism. Purportedly, David Foster Wallace bound his hands together when he hung himself, possibly due to an understanding that he might have a change of heart. However, it is important to remember that suicides often are not thought out, Robin Williams decided to use his own belt buckle tighten on one side with the other wedged between the closet door and it's respective jam.
[^11]: From both a research and anecdote perspective, that dehydration and neural decrease that follows a heavy day(into)night drinking predicts a particularly low level of cognitive abilities the next day. Which is one of my favorite excuses of all time due to its' relatability in all cases - "I usually don't act like this, I'm just real hungover today.". However, it opens up a whole series of questions - one of the questions might be, How long can you keep using this excuse?
[^12]: Appreciated is all together the wrong word used here. Rather, some orgiastic awakening through violent abusive force alone.
[^13]: Unsympathetically, this is one of the most popular Belgian beers with a fantastic pink elephant logo. Who in fact, won "best beer in the world" in 1997. 
[^14]: While there is a massive amount of supporting anecdotes in the recovery community, PAW tends to be less scientifically supported and fairly difficult to measure/diagnose. The *Diagnostic and Statistical Manual of Mental Disorders* simply does not have the academic purview to understand that symptoms such as insomnia, anxiety, or agitation, may persist for longer than a 12-month period.
[^15]: A rocket headed straight for a mountain full of explosives may be a better analogy.
[^16]: "Now serving, Life-Lite! Half the amount of emotions but the same overwhelming amount of agony and despair"
[^17]: Things I have broken: two chairs, one laptop, one vacuum, three cups, one microwave, countless plastic trinkets, my relationship with my family, self-esteem, and one night I shouted at nothing until I lost my voice. 
[^18]: A common theme for relapse: "if being clean feels this badly, I might as well just go back." 
[^19]: When reading through Burroughs' notes, a common theme that this loss is his "Greatest Ugly Spirit" which compels him to write his way out (maybe as an act of penance) of a dark, ugly, space in which fiction and reality are blended by any substance. 
[^20]: The cognitive phenomenon of repeating something over and over until it becomes a strange, incomprehensible, meaningless string of letters that holds no semblance of meaning in the english language. 
