---
title: "E.C.C"
author: "Ben Chu"
date: "November 28, 2018"
output: html_document
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)

setwd("C:/Users/Branly Mclanbry/Documents/GitHub/Wordpress")
library(RWordPress)
library(knitr)

options(WordpressLogin = c('chubenn' = 'FarsightedFlamingo1'),
        WordpressURL = 'https://chubenn.blog/xmlrpc.php')

knit2wp("ecc.Rmd", title = "E.C.C.", action = c("newPost"), publish = FALSE)
```

|      I first read Gordon Finch's *Song and Dance*[^1] in the morning of Standard Time, specifically, later in the morning than Daylight Saving Time [^2] because of routine, and not my clock. Prolegomeously [^3], the story starts off with what, in a direction that you've long been accustomed to, appears inviting if not for the cosmic horror. I've long been a rabid fan of G.F. and particularly, his arguments. His early prose would convince even the most devoutly corrupt politicians to give up their stance of misanthropy and join a reclusive Franciscan Cluster in the Honduras. One conversation we had especially inspired me to develop my own character's dialogue. Maybe this writer [^4] is over-extolling the value of relatable dialogue, but digression is more alluring than disillusioning. I believe we were at *Blackbird Coffee* in Chico, CA. 

|      G.F. holds both an almond muffin and my draft at the time. "Hey, Grant, you know people don't talk like that right?"

|      I look across the table toward him. "What do you mean?"

|      He flops the draft down first, then the muffin. "Well look man, people take breaths in-between sentences and allow for responses. C'mon - if they are listening. Nobody goes on long winded Dickens-esque rants."

|      After that I allowed my characters and sentences to inhale then exhale. Gave them space. Used periods. Some sentences can be drawn out and stretched, like the waves on the ocean - pulsating and palpitating in and out and rolling endlessly. Freeze unannounced. Then resume onto a long winded sentence that desiderates cadence and pacing while touching off with a sweet resolution.    
|      Later in the conversation, we were discussing the raw power of description in Burroughs's Naked Lunch and how its suppuration filled my cancer-ridden bones, which is similarly evident in SAD. Gruesomely conjoint and conjoined gruesomely. 
|      I guess I should provide some review on *SAD* - it may be appropriate given these politically-minded November nights. *SAD* is his own eruditic Cronenberg creature, giving in to the details of people and environments only found in cult-based horror [^5]. The crux of the action sparks surprisingly out of nowhere, as if stirring your tea with a honey stick only to realize that it was the 10mg THC honey stick that you purchased from the dispensary last week [^6]. SAD unravels the hero of the story, who, framed in the final moment of a bloody-knuckle clutch of glory is found to be, maybe one of us. Maybe. The story of the unknown hero warding off another bout of internal cravenness might be what we need. (INTERPOLATION - That following Thursday, The United States went to the voting booths to dictate what direction the midterms would head. Blocked polling places; determining - not disheartening. I can't remark particularly on the population's virtues, but there is one great nescient American foible - to maliciously vote solely because of opposition. As the barflies downing their Sunday Coffee's would say "Is it brilliant? No, but fuck yea.")
|      Lastly, the ending is quite poignant, something that I needed to hear, like finding another layer in Ocampo's *Jimmy Carter*. I hearken to a time as an adolescent, watching fire leave behind grey indiscernible ash layered in satisfaction and denouement[^7]. G.F. compels you with a quality of thought-voice that is uniquely his[^8] and *SAD* sidesaddles the despondency of our modern politics. He makes the often misunderstood criticism that though we are simple beasts who follow the same timeline, it's still going to be okay. We are currently alive, and that merits action and effort. Even for one last attempt at climbing the vertiginous *Chichen Itza* in our tenebrous lives. Though, I could be entirely wrong, maybe we should just take it as his performance in storytelling, which, in our climate of furious fires, brings the fresh flood that includes a beginning, middle, and end.
|      Later on the evening of my first read through, the sun would set one hour earlier, clockwise, than I am used to. OKAY! I would begin my slumber ritual at the time the clock would suggest, which would devastate my body in terms of cognitive load. That is, *SAD-ly*, as the same young adolescent who collapses into a multitude of hands, basking in exaltation from all the strain from the marathon of one extra hour.

[^1]: In issue VI of *Poverty Scam*, 2018. Hard copies are near impossible to find and the website alludes to a dystopian Brazilian future where trickeries are considered kosher in their unspoken constitution.
[^2]: Three quick notes on the misconception surrounding DST: *(1)* when people complain during that first dark night in November, they are often complaining about the hasteful movement towards dusk and usually say something to the effect of "It's so dark, why do we even use Daylight Savings anymore?" The rhetoric is notoriously fraught with negative sentiment which usually suggests a desire of the removal of DST. Uncoveredly, they really mean to do away with Standard Time (which seeks to confuse and oppress followers of Itzamna, but only during the winter). *(2)* Daylight savings time wasn't invented for farmers or anything of that ilk, rather for businesses - unsurprisingly. One more daylight hour = One more business hour. *(3)* The "Savings" in DST is simply a misnomer - you aren't saving time or energy or America. **Business Retail Time** would be much more appropriate. It's easy to imagine the ad spots now: "It's dark outside! Bring your kids!" 
[^3]: I should preface, that if you have not read *SAD*, let this serve as a contextual preamble and skip the next sentence. If you have read it, then nod your head with me in agreement right now. Fantastic.
[^4]: Am I a human? Or am I a writer?
[^5]: A short few lines underline the disastrous passion for pain that can be found in any gathering of people, in which they start to group hoards of people together based on nothing more than geography or education or the language^5a^ we use or hat color or even down to the most controversial orgasm-location preference ^5b^ . Maybe more so than this, G.F.'s "Great Variance of Terminology" really unloads on the sense of organization that hatred, founded in our moral system, can motivate us into action. That is, it enables him to heavily dramatize the seriousness of discrimination without seeming egregiously sanctimonious like 'The Speaker', whom is the primary target of his criticism.(5a)  I remember in middle school when a group of students who sat far from the cafeteria food line were 'crap-heads' because their parents could afford to provide them with *Lunchables* instead of generic school food. (5b) There is one confession I must make, my perspective on this **exact** topic was the subject of my thesis during my  time in Academia. 
[^6]: The expectations, dialogue, and process involved in legally purchasing cannabidiol products from dispensaries is both underwhelming and confirming. Consider this, retail business tend to employ people who are familiar with their own product; bicycle shops are filled with extreme bikers who take it to the max, chefs who have a delicate penchant for the hidden and subtle can be found in restaurants, dispensaries however, are filled with stoners who smoke. A lot. This tends to lead to a mismatch between the consumer and salesperson. Where the first two were assiduous, the latter is. "chillax brah."
[^7]: Seven of the top twenty most destructive fires in California history happened since the beginning of 2017. 60% of these California's fires occur in forests owned by the Federal Government distributed between the USDA Forest Service, Bureau of Land Management, and the National Park Service. Funding for both prevention and fighting has been severely reduced resulting in both the increased cost overall and indolent relief response. The current administration suggests (instead of scientifically sound methods of clearing underbrush and thinning) clear cutting trees - "can't have a fire if there is nothing to burn" - which indisputably leaves larger amounts of potential fuel. More destructive fires.  November 10th, 2018, 12:08 AM - Donald J. Trump tweeted "There is no reason for . fires in California except that forest management is so poor.... All because of gross mismanagement. Remedy now, or no more Fed payments!" It seems like, to this writer, the poor budget management is found in the subsidy redistribution which gives billions of dollars to wealthy corporations like Sierra Pacific while draining millions of dollars out of the already withered forest management budget.
[^8]: Maybe he IS the Eruditic Cronenberg Creature. E.C.C for short.